### ISSUE TITLE
Using other encoder models

### ISSUE THREAD

**Issue by rahulseetharaman** [martiansideofthemoon/rankgen#18]
Hi @martiansideofthemoon 

Thanks for the awesome repo and paper ! I am trying to use a custom encoder model using sentence transformer, which I want to plug into RankGen (with the RankGenEncoder class). But I am getting this error when doing so, 

```
AssertionError                            Traceback (most recent call last)
[<ipython-input-6-54d53aceef63>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 # rankgen_encoder = RankGenEncoder("kalpeshk2011/rankgen-t5-xl-all")
----> 4 rankgen_encoder = RankGenEncoder("funn/t5-toxicity-ranker")

[/usr/local/lib/python3.10/dist-packages/rankgen/rankgen_encoder.py](https://localhost:8080/#) in __init__(self, model_path, max_batch_size, model_size, cache_dir)
      9 class RankGenEncoder():
     10     def __init__(self, model_path, max_batch_size=32, model_size=None, cache_dir=None):
---> 11         assert model_path in ["kalpeshk2011/rankgen-t5-xl-all", "kalpeshk2011/rankgen-t5-xl-pg19", "kalpeshk2011/rankgen-t5-base-all", "kalpeshk2011/rankgen-t5-large-all"]
     12         self.max_batch_size = max_batch_size
     13         self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
```

Is there any specific reason for using this assert statement ? Does RankGen support other bi-encoder models too ? For context, I am trying to use a T5-base Bi-Encoder model, trained using SBERT.

**Comment by martiansideofthemoon** [comment]
Please comment this line if you want to use custom embedding methods. The reason the line was added in is because RankGen models are trained on a fairly specialized task of prefix-suffix prediction, optimized for generative modeling. Nevertheless, feel free to try other options :)

Closing this for now, please re-open if not resolved.
