### ISSUE TITLE
dataset missing 

### ISSUE THREAD

**Issue by rohitmishra94** [martiansideofthemoon/rankgen#6]
when i ran this part of code python scripts/rankgen_beam_search.py --retriever_model_path rankgen_models/t5_xl_all \
    --num_tokens 20 --num_samples 10 --beam_size 2 --output_file outputs_beam/wiki_t5_xl_beam_2_tokens_20_samples_10.jsonl

it ask for dataset which is not provided?
where to get the dataset

**Comment by martiansideofthemoon** [comment]
hi @rohitmishra94 sorry this slipped my mind. I've pushed a commit fixing this,
https://github.com/martiansideofthemoon/rankgen#running-beam-search-with-rankgen
