### ISSUE TITLE
minimum spec required to run the experiment

### ISSUE THREAD

**Issue by rohitmishra94** [martiansideofthemoon/rankgen#7]
Hi i was trying to run beam search code, but got mem error, I was doing this experiement in aws g4dn x large instance have 16g memory,

what is the minimum specs i need to properly run this?

**Comment by martiansideofthemoon** [comment]
Hi @rohitmishra94, you could try reducing the number of samples generated per instance to reduce memory usage, try `num_samples=5` and `beam_size=2` for instance. Another (slower) option is to do a for loop over `num_samples` here - https://github.com/martiansideofthemoon/rankgen/blob/master/scripts/rankgen_beam_search.py#L103

**Comment by martiansideofthemoon** [comment]
hi @rohitmishra94, we've now uploaded the RankGen-base and RankGen-large models which should run on smaller GPUs (see README). I've also added an open issue #10 to create a Dockerfile for the project.
